select 'Categories', count(*) from [Categories];
select 'CustomerCustomerDemo', count(*) from [CustomerCustomerDemo];
select 'CustomerDemographics', count(*) from [CustomerDemographics];
select 'Customers', count(*) from [Customers];
select 'EmployeeTerritories', count(*) from [EmployeeTerritories];
select 'Employees', count(*) from [Employees];
select 'OrderDetails', count(*) from [Order Details];
select 'Orders', count(*) from [Orders];
select 'Products', count(*) from [Products];
select 'Regions', count(*) from [Regions];
select 'Shippers', count(*) from [Shippers];
select 'Suppliers', count(*) from [Suppliers];
select 'Territories', count(*) from [Territories];
